"""Runtime boundary contracts for thin composition-root architecture."""

from .runtime_contracts import (
    MemoryRequest,
    MemoryResult,
    ResponseOutput,
    ResponseRequest,
    RouterDecision,
    RouterRequest,
    RuntimeBoundaries,
    ToolInvocation,
    ToolResult,
    VerifierRequest,
    VerifierResult,
)
from .default_adapters import (
    CallableMemoryAdapter,
    CallableResponseAdapter,
    CallableRoutingAdapter,
    CallableToolAdapter,
    CallableVerifierAdapter,
)
from .tool_schema import (
    ToolSchemaValidationError,
    validate_tool_invocation_payload,
    validate_tool_result_payload,
)
from .interfaces import (
    ChatMessage,
    ChatResponse,
    CompanionRuntimeProtocol,
    EmotionResult,
    ExecutiveControllerProtocol,
    ExecutionResult,
    LLMEngineProtocol,
    MemoryStoreProtocol,
    NLPEngineProtocol,
    PolicyDecision,
    RouteDecision,
    RouteResult,
    SafetyLevel,
    SlotFillerResult,
    TemporalParseResult,
    ToolCall,
    TurnStateMachineResult,
    VerificationResult,
)

__all__ = [
    "RouterRequest",
    "RouterDecision",
    "MemoryRequest",
    "MemoryResult",
    "ToolInvocation",
    "ToolResult",
    "ResponseRequest",
    "ResponseOutput",
    "RuntimeBoundaries",
    "VerifierRequest",
    "VerifierResult",
    "CallableRoutingAdapter",
    "CallableMemoryAdapter",
    "CallableToolAdapter",
    "CallableResponseAdapter",
    "CallableVerifierAdapter",
    "ToolSchemaValidationError",
    "validate_tool_invocation_payload",
    "validate_tool_result_payload",
    "RouteDecision",
    "RouteResult",
    "ChatMessage",
    "ToolCall",
    "ChatResponse",
    "SlotFillerResult",
    "TemporalParseResult",
    "EmotionResult",
    "SafetyLevel",
    "PolicyDecision",
    "VerificationResult",
    "ExecutionResult",
    "TurnStateMachineResult",
    "ExecutiveControllerProtocol",
    "CompanionRuntimeProtocol",
    "NLPEngineProtocol",
    "LLMEngineProtocol",
    "MemoryStoreProtocol",
]
